version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_UNIFY_CONTROLLER_IP
      APP_PORT: 8443
      PROXY_AUTH_ADD: "false"

  server:
    image: linuxserver/unifi-controller:7.2.92
    # user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
    volumes:
      - ${APP_DATA_DIR}/data:/config
    networks:
      default:
        ipv4_address: $APP_UNIFY_CONTROLLER_IP
